/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class call_filter_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"call_filter_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"label\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"number\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"result_size\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public java.lang.CharSequence label;
  @Deprecated public java.lang.CharSequence number;
  @Deprecated public java.lang.Integer result_size;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public call_filter_record() {}

  /**
   * All-args constructor.
   */
  public call_filter_record(java.lang.CharSequence action, java.lang.CharSequence label, java.lang.CharSequence number, java.lang.Integer result_size) {
    this.action = action;
    this.label = label;
    this.number = number;
    this.result_size = result_size;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return action;
    case 1: return label;
    case 2: return number;
    case 3: return result_size;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: action = (java.lang.CharSequence)value$; break;
    case 1: label = (java.lang.CharSequence)value$; break;
    case 2: number = (java.lang.CharSequence)value$; break;
    case 3: result_size = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'number' field.
   */
  public java.lang.CharSequence getNumber() {
    return number;
  }

  /**
   * Sets the value of the 'number' field.
   * @param value the value to set.
   */
  public void setNumber(java.lang.CharSequence value) {
    this.number = value;
  }

  /**
   * Gets the value of the 'result_size' field.
   */
  public java.lang.Integer getResultSize() {
    return result_size;
  }

  /**
   * Sets the value of the 'result_size' field.
   * @param value the value to set.
   */
  public void setResultSize(java.lang.Integer value) {
    this.result_size = value;
  }

  /** Creates a new call_filter_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.call_filter_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.call_filter_record.Builder();
  }
  
  /** Creates a new call_filter_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.call_filter_record.Builder newBuilder(com.truecaller.logging.kafka.events.call_filter_record.Builder other) {
    return new com.truecaller.logging.kafka.events.call_filter_record.Builder(other);
  }
  
  /** Creates a new call_filter_record RecordBuilder by copying an existing call_filter_record instance */
  public static com.truecaller.logging.kafka.events.call_filter_record.Builder newBuilder(com.truecaller.logging.kafka.events.call_filter_record other) {
    return new com.truecaller.logging.kafka.events.call_filter_record.Builder(other);
  }
  
  /**
   * RecordBuilder for call_filter_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<call_filter_record>
    implements org.apache.avro.data.RecordBuilder<call_filter_record> {

    private java.lang.CharSequence action;
    private java.lang.CharSequence label;
    private java.lang.CharSequence number;
    private java.lang.Integer result_size;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.call_filter_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.call_filter_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.number)) {
        this.number = data().deepCopy(fields()[2].schema(), other.number);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.result_size)) {
        this.result_size = data().deepCopy(fields()[3].schema(), other.result_size);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing call_filter_record instance */
    private Builder(com.truecaller.logging.kafka.events.call_filter_record other) {
            super(com.truecaller.logging.kafka.events.call_filter_record.SCHEMA$);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.number)) {
        this.number = data().deepCopy(fields()[2].schema(), other.number);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.result_size)) {
        this.result_size = data().deepCopy(fields()[3].schema(), other.result_size);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'action' field */
    public java.lang.CharSequence getAction() {
      return action;
    }
    
    /** Sets the value of the 'action' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.action = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'action' field has been set */
    public boolean hasAction() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'action' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder clearAction() {
      action = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'label' field */
    public java.lang.CharSequence getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'label' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder clearLabel() {
      label = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'number' field */
    public java.lang.CharSequence getNumber() {
      return number;
    }
    
    /** Sets the value of the 'number' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder setNumber(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.number = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'number' field has been set */
    public boolean hasNumber() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'number' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder clearNumber() {
      number = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'result_size' field */
    public java.lang.Integer getResultSize() {
      return result_size;
    }
    
    /** Sets the value of the 'result_size' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder setResultSize(java.lang.Integer value) {
      validate(fields()[3], value);
      this.result_size = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'result_size' field has been set */
    public boolean hasResultSize() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'result_size' field */
    public com.truecaller.logging.kafka.events.call_filter_record.Builder clearResultSize() {
      result_size = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public call_filter_record build() {
      try {
        call_filter_record record = new call_filter_record();
        record.action = fieldSetFlags()[0] ? this.action : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.label = fieldSetFlags()[1] ? this.label : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.number = fieldSetFlags()[2] ? this.number : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.result_size = fieldSetFlags()[3] ? this.result_size : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
