/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class contacts_upload_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"contacts_upload_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"contacts\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"upload_contact_record\",\"fields\":[{\"name\":\"phone\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"social_ids\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public java.util.List<com.truecaller.logging.kafka.events.upload_contact_record> contacts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public contacts_upload_record() {}

  /**
   * All-args constructor.
   */
  public contacts_upload_record(java.lang.CharSequence action, java.util.List<com.truecaller.logging.kafka.events.upload_contact_record> contacts) {
    this.action = action;
    this.contacts = contacts;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return action;
    case 1: return contacts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: action = (java.lang.CharSequence)value$; break;
    case 1: contacts = (java.util.List<com.truecaller.logging.kafka.events.upload_contact_record>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'contacts' field.
   */
  public java.util.List<com.truecaller.logging.kafka.events.upload_contact_record> getContacts() {
    return contacts;
  }

  /**
   * Sets the value of the 'contacts' field.
   * @param value the value to set.
   */
  public void setContacts(java.util.List<com.truecaller.logging.kafka.events.upload_contact_record> value) {
    this.contacts = value;
  }

  /** Creates a new contacts_upload_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.contacts_upload_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.contacts_upload_record.Builder();
  }
  
  /** Creates a new contacts_upload_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.contacts_upload_record.Builder newBuilder(com.truecaller.logging.kafka.events.contacts_upload_record.Builder other) {
    return new com.truecaller.logging.kafka.events.contacts_upload_record.Builder(other);
  }
  
  /** Creates a new contacts_upload_record RecordBuilder by copying an existing contacts_upload_record instance */
  public static com.truecaller.logging.kafka.events.contacts_upload_record.Builder newBuilder(com.truecaller.logging.kafka.events.contacts_upload_record other) {
    return new com.truecaller.logging.kafka.events.contacts_upload_record.Builder(other);
  }
  
  /**
   * RecordBuilder for contacts_upload_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<contacts_upload_record>
    implements org.apache.avro.data.RecordBuilder<contacts_upload_record> {

    private java.lang.CharSequence action;
    private java.util.List<com.truecaller.logging.kafka.events.upload_contact_record> contacts;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.contacts_upload_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.contacts_upload_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contacts)) {
        this.contacts = data().deepCopy(fields()[1].schema(), other.contacts);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing contacts_upload_record instance */
    private Builder(com.truecaller.logging.kafka.events.contacts_upload_record other) {
            super(com.truecaller.logging.kafka.events.contacts_upload_record.SCHEMA$);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contacts)) {
        this.contacts = data().deepCopy(fields()[1].schema(), other.contacts);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'action' field */
    public java.lang.CharSequence getAction() {
      return action;
    }
    
    /** Sets the value of the 'action' field */
    public com.truecaller.logging.kafka.events.contacts_upload_record.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.action = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'action' field has been set */
    public boolean hasAction() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'action' field */
    public com.truecaller.logging.kafka.events.contacts_upload_record.Builder clearAction() {
      action = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'contacts' field */
    public java.util.List<com.truecaller.logging.kafka.events.upload_contact_record> getContacts() {
      return contacts;
    }
    
    /** Sets the value of the 'contacts' field */
    public com.truecaller.logging.kafka.events.contacts_upload_record.Builder setContacts(java.util.List<com.truecaller.logging.kafka.events.upload_contact_record> value) {
      validate(fields()[1], value);
      this.contacts = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'contacts' field has been set */
    public boolean hasContacts() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'contacts' field */
    public com.truecaller.logging.kafka.events.contacts_upload_record.Builder clearContacts() {
      contacts = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public contacts_upload_record build() {
      try {
        contacts_upload_record record = new contacts_upload_record();
        record.action = fieldSetFlags()[0] ? this.action : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.contacts = fieldSetFlags()[1] ? this.contacts : (java.util.List<com.truecaller.logging.kafka.events.upload_contact_record>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
