/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class contact_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"contact_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"msg_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"msg_language\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public java.lang.CharSequence status;
  @Deprecated public java.lang.CharSequence msg_id;
  @Deprecated public java.lang.CharSequence msg_language;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public contact_record() {}

  /**
   * All-args constructor.
   */
  public contact_record(java.lang.CharSequence action, java.lang.CharSequence status, java.lang.CharSequence msg_id, java.lang.CharSequence msg_language) {
    this.action = action;
    this.status = status;
    this.msg_id = msg_id;
    this.msg_language = msg_language;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return action;
    case 1: return status;
    case 2: return msg_id;
    case 3: return msg_language;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: action = (java.lang.CharSequence)value$; break;
    case 1: status = (java.lang.CharSequence)value$; break;
    case 2: msg_id = (java.lang.CharSequence)value$; break;
    case 3: msg_language = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'msg_id' field.
   */
  public java.lang.CharSequence getMsgId() {
    return msg_id;
  }

  /**
   * Sets the value of the 'msg_id' field.
   * @param value the value to set.
   */
  public void setMsgId(java.lang.CharSequence value) {
    this.msg_id = value;
  }

  /**
   * Gets the value of the 'msg_language' field.
   */
  public java.lang.CharSequence getMsgLanguage() {
    return msg_language;
  }

  /**
   * Sets the value of the 'msg_language' field.
   * @param value the value to set.
   */
  public void setMsgLanguage(java.lang.CharSequence value) {
    this.msg_language = value;
  }

  /** Creates a new contact_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.contact_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.contact_record.Builder();
  }
  
  /** Creates a new contact_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.contact_record.Builder newBuilder(com.truecaller.logging.kafka.events.contact_record.Builder other) {
    return new com.truecaller.logging.kafka.events.contact_record.Builder(other);
  }
  
  /** Creates a new contact_record RecordBuilder by copying an existing contact_record instance */
  public static com.truecaller.logging.kafka.events.contact_record.Builder newBuilder(com.truecaller.logging.kafka.events.contact_record other) {
    return new com.truecaller.logging.kafka.events.contact_record.Builder(other);
  }
  
  /**
   * RecordBuilder for contact_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<contact_record>
    implements org.apache.avro.data.RecordBuilder<contact_record> {

    private java.lang.CharSequence action;
    private java.lang.CharSequence status;
    private java.lang.CharSequence msg_id;
    private java.lang.CharSequence msg_language;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.contact_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.contact_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_id)) {
        this.msg_id = data().deepCopy(fields()[2].schema(), other.msg_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.msg_language)) {
        this.msg_language = data().deepCopy(fields()[3].schema(), other.msg_language);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing contact_record instance */
    private Builder(com.truecaller.logging.kafka.events.contact_record other) {
            super(com.truecaller.logging.kafka.events.contact_record.SCHEMA$);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.msg_id)) {
        this.msg_id = data().deepCopy(fields()[2].schema(), other.msg_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.msg_language)) {
        this.msg_language = data().deepCopy(fields()[3].schema(), other.msg_language);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'action' field */
    public java.lang.CharSequence getAction() {
      return action;
    }
    
    /** Sets the value of the 'action' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.action = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'action' field has been set */
    public boolean hasAction() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'action' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder clearAction() {
      action = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.CharSequence getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'status' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'msg_id' field */
    public java.lang.CharSequence getMsgId() {
      return msg_id;
    }
    
    /** Sets the value of the 'msg_id' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder setMsgId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.msg_id = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'msg_id' field has been set */
    public boolean hasMsgId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'msg_id' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder clearMsgId() {
      msg_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'msg_language' field */
    public java.lang.CharSequence getMsgLanguage() {
      return msg_language;
    }
    
    /** Sets the value of the 'msg_language' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder setMsgLanguage(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.msg_language = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'msg_language' field has been set */
    public boolean hasMsgLanguage() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'msg_language' field */
    public com.truecaller.logging.kafka.events.contact_record.Builder clearMsgLanguage() {
      msg_language = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public contact_record build() {
      try {
        contact_record record = new contact_record();
        record.action = fieldSetFlags()[0] ? this.action : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.msg_id = fieldSetFlags()[2] ? this.msg_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.msg_language = fieldSetFlags()[3] ? this.msg_language : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
