/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class credits_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"credits_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"transaction_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"added_credits\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"package\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public java.lang.CharSequence transaction_id;
  @Deprecated public java.lang.Integer added_credits;
  @Deprecated public java.lang.CharSequence package$;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public credits_record() {}

  /**
   * All-args constructor.
   */
  public credits_record(java.lang.CharSequence action, java.lang.CharSequence transaction_id, java.lang.Integer added_credits, java.lang.CharSequence package$) {
    this.action = action;
    this.transaction_id = transaction_id;
    this.added_credits = added_credits;
    this.package$ = package$;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return action;
    case 1: return transaction_id;
    case 2: return added_credits;
    case 3: return package$;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: action = (java.lang.CharSequence)value$; break;
    case 1: transaction_id = (java.lang.CharSequence)value$; break;
    case 2: added_credits = (java.lang.Integer)value$; break;
    case 3: package$ = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'transaction_id' field.
   */
  public java.lang.CharSequence getTransactionId() {
    return transaction_id;
  }

  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.CharSequence value) {
    this.transaction_id = value;
  }

  /**
   * Gets the value of the 'added_credits' field.
   */
  public java.lang.Integer getAddedCredits() {
    return added_credits;
  }

  /**
   * Sets the value of the 'added_credits' field.
   * @param value the value to set.
   */
  public void setAddedCredits(java.lang.Integer value) {
    this.added_credits = value;
  }

  /**
   * Gets the value of the 'package$' field.
   */
  public java.lang.CharSequence getPackage$() {
    return package$;
  }

  /**
   * Sets the value of the 'package$' field.
   * @param value the value to set.
   */
  public void setPackage$(java.lang.CharSequence value) {
    this.package$ = value;
  }

  /** Creates a new credits_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.credits_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.credits_record.Builder();
  }
  
  /** Creates a new credits_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.credits_record.Builder newBuilder(com.truecaller.logging.kafka.events.credits_record.Builder other) {
    return new com.truecaller.logging.kafka.events.credits_record.Builder(other);
  }
  
  /** Creates a new credits_record RecordBuilder by copying an existing credits_record instance */
  public static com.truecaller.logging.kafka.events.credits_record.Builder newBuilder(com.truecaller.logging.kafka.events.credits_record other) {
    return new com.truecaller.logging.kafka.events.credits_record.Builder(other);
  }
  
  /**
   * RecordBuilder for credits_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<credits_record>
    implements org.apache.avro.data.RecordBuilder<credits_record> {

    private java.lang.CharSequence action;
    private java.lang.CharSequence transaction_id;
    private java.lang.Integer added_credits;
    private java.lang.CharSequence package$;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.credits_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.credits_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[1].schema(), other.transaction_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.added_credits)) {
        this.added_credits = data().deepCopy(fields()[2].schema(), other.added_credits);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.package$)) {
        this.package$ = data().deepCopy(fields()[3].schema(), other.package$);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing credits_record instance */
    private Builder(com.truecaller.logging.kafka.events.credits_record other) {
            super(com.truecaller.logging.kafka.events.credits_record.SCHEMA$);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[1].schema(), other.transaction_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.added_credits)) {
        this.added_credits = data().deepCopy(fields()[2].schema(), other.added_credits);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.package$)) {
        this.package$ = data().deepCopy(fields()[3].schema(), other.package$);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'action' field */
    public java.lang.CharSequence getAction() {
      return action;
    }
    
    /** Sets the value of the 'action' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.action = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'action' field has been set */
    public boolean hasAction() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'action' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder clearAction() {
      action = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'transaction_id' field */
    public java.lang.CharSequence getTransactionId() {
      return transaction_id;
    }
    
    /** Sets the value of the 'transaction_id' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder setTransactionId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.transaction_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'transaction_id' field has been set */
    public boolean hasTransactionId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'transaction_id' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'added_credits' field */
    public java.lang.Integer getAddedCredits() {
      return added_credits;
    }
    
    /** Sets the value of the 'added_credits' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder setAddedCredits(java.lang.Integer value) {
      validate(fields()[2], value);
      this.added_credits = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'added_credits' field has been set */
    public boolean hasAddedCredits() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'added_credits' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder clearAddedCredits() {
      added_credits = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'package$' field */
    public java.lang.CharSequence getPackage$() {
      return package$;
    }
    
    /** Sets the value of the 'package$' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder setPackage$(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.package$ = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'package$' field has been set */
    public boolean hasPackage$() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'package$' field */
    public com.truecaller.logging.kafka.events.credits_record.Builder clearPackage$() {
      package$ = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public credits_record build() {
      try {
        credits_record record = new credits_record();
        record.action = fieldSetFlags()[0] ? this.action : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.transaction_id = fieldSetFlags()[1] ? this.transaction_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.added_credits = fieldSetFlags()[2] ? this.added_credits : (java.lang.Integer) defaultValue(fields()[2]);
        record.package$ = fieldSetFlags()[3] ? this.package$ : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
