/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class daily_counters_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"daily_counters_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"label\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"count\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence label;
  @Deprecated public java.lang.Integer count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public daily_counters_record() {}

  /**
   * All-args constructor.
   */
  public daily_counters_record(java.lang.CharSequence label, java.lang.Integer count) {
    this.label = label;
    this.count = count;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return label;
    case 1: return count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: label = (java.lang.CharSequence)value$; break;
    case 1: count = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'count' field.
   */
  public java.lang.Integer getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Integer value) {
    this.count = value;
  }

  /** Creates a new daily_counters_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.daily_counters_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.daily_counters_record.Builder();
  }
  
  /** Creates a new daily_counters_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.daily_counters_record.Builder newBuilder(com.truecaller.logging.kafka.events.daily_counters_record.Builder other) {
    return new com.truecaller.logging.kafka.events.daily_counters_record.Builder(other);
  }
  
  /** Creates a new daily_counters_record RecordBuilder by copying an existing daily_counters_record instance */
  public static com.truecaller.logging.kafka.events.daily_counters_record.Builder newBuilder(com.truecaller.logging.kafka.events.daily_counters_record other) {
    return new com.truecaller.logging.kafka.events.daily_counters_record.Builder(other);
  }
  
  /**
   * RecordBuilder for daily_counters_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<daily_counters_record>
    implements org.apache.avro.data.RecordBuilder<daily_counters_record> {

    private java.lang.CharSequence label;
    private java.lang.Integer count;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.daily_counters_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.daily_counters_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.label)) {
        this.label = data().deepCopy(fields()[0].schema(), other.label);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count)) {
        this.count = data().deepCopy(fields()[1].schema(), other.count);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing daily_counters_record instance */
    private Builder(com.truecaller.logging.kafka.events.daily_counters_record other) {
            super(com.truecaller.logging.kafka.events.daily_counters_record.SCHEMA$);
      if (isValidValue(fields()[0], other.label)) {
        this.label = data().deepCopy(fields()[0].schema(), other.label);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.count)) {
        this.count = data().deepCopy(fields()[1].schema(), other.count);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'label' field */
    public java.lang.CharSequence getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public com.truecaller.logging.kafka.events.daily_counters_record.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.label = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'label' field */
    public com.truecaller.logging.kafka.events.daily_counters_record.Builder clearLabel() {
      label = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'count' field */
    public java.lang.Integer getCount() {
      return count;
    }
    
    /** Sets the value of the 'count' field */
    public com.truecaller.logging.kafka.events.daily_counters_record.Builder setCount(java.lang.Integer value) {
      validate(fields()[1], value);
      this.count = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'count' field has been set */
    public boolean hasCount() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'count' field */
    public com.truecaller.logging.kafka.events.daily_counters_record.Builder clearCount() {
      count = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public daily_counters_record build() {
      try {
        daily_counters_record record = new daily_counters_record();
        record.label = fieldSetFlags()[0] ? this.label : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.count = fieldSetFlags()[1] ? this.count : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
