/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class people_you_may_know_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"people_you_may_know_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"page\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public java.lang.Integer page;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public people_you_may_know_record() {}

  /**
   * All-args constructor.
   */
  public people_you_may_know_record(java.lang.CharSequence action, java.lang.Integer page) {
    this.action = action;
    this.page = page;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return action;
    case 1: return page;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: action = (java.lang.CharSequence)value$; break;
    case 1: page = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'page' field.
   */
  public java.lang.Integer getPage() {
    return page;
  }

  /**
   * Sets the value of the 'page' field.
   * @param value the value to set.
   */
  public void setPage(java.lang.Integer value) {
    this.page = value;
  }

  /** Creates a new people_you_may_know_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.people_you_may_know_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.people_you_may_know_record.Builder();
  }
  
  /** Creates a new people_you_may_know_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.people_you_may_know_record.Builder newBuilder(com.truecaller.logging.kafka.events.people_you_may_know_record.Builder other) {
    return new com.truecaller.logging.kafka.events.people_you_may_know_record.Builder(other);
  }
  
  /** Creates a new people_you_may_know_record RecordBuilder by copying an existing people_you_may_know_record instance */
  public static com.truecaller.logging.kafka.events.people_you_may_know_record.Builder newBuilder(com.truecaller.logging.kafka.events.people_you_may_know_record other) {
    return new com.truecaller.logging.kafka.events.people_you_may_know_record.Builder(other);
  }
  
  /**
   * RecordBuilder for people_you_may_know_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<people_you_may_know_record>
    implements org.apache.avro.data.RecordBuilder<people_you_may_know_record> {

    private java.lang.CharSequence action;
    private java.lang.Integer page;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.people_you_may_know_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.people_you_may_know_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.page)) {
        this.page = data().deepCopy(fields()[1].schema(), other.page);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing people_you_may_know_record instance */
    private Builder(com.truecaller.logging.kafka.events.people_you_may_know_record other) {
            super(com.truecaller.logging.kafka.events.people_you_may_know_record.SCHEMA$);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.page)) {
        this.page = data().deepCopy(fields()[1].schema(), other.page);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'action' field */
    public java.lang.CharSequence getAction() {
      return action;
    }
    
    /** Sets the value of the 'action' field */
    public com.truecaller.logging.kafka.events.people_you_may_know_record.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.action = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'action' field has been set */
    public boolean hasAction() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'action' field */
    public com.truecaller.logging.kafka.events.people_you_may_know_record.Builder clearAction() {
      action = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'page' field */
    public java.lang.Integer getPage() {
      return page;
    }
    
    /** Sets the value of the 'page' field */
    public com.truecaller.logging.kafka.events.people_you_may_know_record.Builder setPage(java.lang.Integer value) {
      validate(fields()[1], value);
      this.page = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'page' field has been set */
    public boolean hasPage() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'page' field */
    public com.truecaller.logging.kafka.events.people_you_may_know_record.Builder clearPage() {
      page = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public people_you_may_know_record build() {
      try {
        people_you_may_know_record record = new people_you_may_know_record();
        record.action = fieldSetFlags()[0] ? this.action : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.page = fieldSetFlags()[1] ? this.page : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
