/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class social_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"social_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence action;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public social_record() {}

  /**
   * All-args constructor.
   */
  public social_record(java.lang.CharSequence action) {
    this.action = action;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return action;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: action = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /** Creates a new social_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.social_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.social_record.Builder();
  }
  
  /** Creates a new social_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.social_record.Builder newBuilder(com.truecaller.logging.kafka.events.social_record.Builder other) {
    return new com.truecaller.logging.kafka.events.social_record.Builder(other);
  }
  
  /** Creates a new social_record RecordBuilder by copying an existing social_record instance */
  public static com.truecaller.logging.kafka.events.social_record.Builder newBuilder(com.truecaller.logging.kafka.events.social_record other) {
    return new com.truecaller.logging.kafka.events.social_record.Builder(other);
  }
  
  /**
   * RecordBuilder for social_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<social_record>
    implements org.apache.avro.data.RecordBuilder<social_record> {

    private java.lang.CharSequence action;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.social_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.social_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing social_record instance */
    private Builder(com.truecaller.logging.kafka.events.social_record other) {
            super(com.truecaller.logging.kafka.events.social_record.SCHEMA$);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'action' field */
    public java.lang.CharSequence getAction() {
      return action;
    }
    
    /** Sets the value of the 'action' field */
    public com.truecaller.logging.kafka.events.social_record.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.action = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'action' field has been set */
    public boolean hasAction() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'action' field */
    public com.truecaller.logging.kafka.events.social_record.Builder clearAction() {
      action = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public social_record build() {
      try {
        social_record record = new social_record();
        record.action = fieldSetFlags()[0] ? this.action : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
