/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class user_account_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"user_account_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"action\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"verified\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"secret_token\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"token_status\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public java.lang.Integer verified;
  @Deprecated public java.lang.CharSequence secret_token;
  @Deprecated public java.lang.CharSequence token_status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public user_account_record() {}

  /**
   * All-args constructor.
   */
  public user_account_record(java.lang.CharSequence action, java.lang.Integer verified, java.lang.CharSequence secret_token, java.lang.CharSequence token_status) {
    this.action = action;
    this.verified = verified;
    this.secret_token = secret_token;
    this.token_status = token_status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return action;
    case 1: return verified;
    case 2: return secret_token;
    case 3: return token_status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: action = (java.lang.CharSequence)value$; break;
    case 1: verified = (java.lang.Integer)value$; break;
    case 2: secret_token = (java.lang.CharSequence)value$; break;
    case 3: token_status = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }

  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'verified' field.
   */
  public java.lang.Integer getVerified() {
    return verified;
  }

  /**
   * Sets the value of the 'verified' field.
   * @param value the value to set.
   */
  public void setVerified(java.lang.Integer value) {
    this.verified = value;
  }

  /**
   * Gets the value of the 'secret_token' field.
   */
  public java.lang.CharSequence getSecretToken() {
    return secret_token;
  }

  /**
   * Sets the value of the 'secret_token' field.
   * @param value the value to set.
   */
  public void setSecretToken(java.lang.CharSequence value) {
    this.secret_token = value;
  }

  /**
   * Gets the value of the 'token_status' field.
   */
  public java.lang.CharSequence getTokenStatus() {
    return token_status;
  }

  /**
   * Sets the value of the 'token_status' field.
   * @param value the value to set.
   */
  public void setTokenStatus(java.lang.CharSequence value) {
    this.token_status = value;
  }

  /** Creates a new user_account_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.user_account_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.user_account_record.Builder();
  }
  
  /** Creates a new user_account_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.user_account_record.Builder newBuilder(com.truecaller.logging.kafka.events.user_account_record.Builder other) {
    return new com.truecaller.logging.kafka.events.user_account_record.Builder(other);
  }
  
  /** Creates a new user_account_record RecordBuilder by copying an existing user_account_record instance */
  public static com.truecaller.logging.kafka.events.user_account_record.Builder newBuilder(com.truecaller.logging.kafka.events.user_account_record other) {
    return new com.truecaller.logging.kafka.events.user_account_record.Builder(other);
  }
  
  /**
   * RecordBuilder for user_account_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<user_account_record>
    implements org.apache.avro.data.RecordBuilder<user_account_record> {

    private java.lang.CharSequence action;
    private java.lang.Integer verified;
    private java.lang.CharSequence secret_token;
    private java.lang.CharSequence token_status;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.user_account_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.user_account_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.verified)) {
        this.verified = data().deepCopy(fields()[1].schema(), other.verified);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.secret_token)) {
        this.secret_token = data().deepCopy(fields()[2].schema(), other.secret_token);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.token_status)) {
        this.token_status = data().deepCopy(fields()[3].schema(), other.token_status);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing user_account_record instance */
    private Builder(com.truecaller.logging.kafka.events.user_account_record other) {
            super(com.truecaller.logging.kafka.events.user_account_record.SCHEMA$);
      if (isValidValue(fields()[0], other.action)) {
        this.action = data().deepCopy(fields()[0].schema(), other.action);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.verified)) {
        this.verified = data().deepCopy(fields()[1].schema(), other.verified);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.secret_token)) {
        this.secret_token = data().deepCopy(fields()[2].schema(), other.secret_token);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.token_status)) {
        this.token_status = data().deepCopy(fields()[3].schema(), other.token_status);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'action' field */
    public java.lang.CharSequence getAction() {
      return action;
    }
    
    /** Sets the value of the 'action' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.action = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'action' field has been set */
    public boolean hasAction() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'action' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder clearAction() {
      action = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'verified' field */
    public java.lang.Integer getVerified() {
      return verified;
    }
    
    /** Sets the value of the 'verified' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder setVerified(java.lang.Integer value) {
      validate(fields()[1], value);
      this.verified = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'verified' field has been set */
    public boolean hasVerified() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'verified' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder clearVerified() {
      verified = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'secret_token' field */
    public java.lang.CharSequence getSecretToken() {
      return secret_token;
    }
    
    /** Sets the value of the 'secret_token' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder setSecretToken(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.secret_token = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'secret_token' field has been set */
    public boolean hasSecretToken() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'secret_token' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder clearSecretToken() {
      secret_token = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'token_status' field */
    public java.lang.CharSequence getTokenStatus() {
      return token_status;
    }
    
    /** Sets the value of the 'token_status' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder setTokenStatus(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.token_status = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'token_status' field has been set */
    public boolean hasTokenStatus() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'token_status' field */
    public com.truecaller.logging.kafka.events.user_account_record.Builder clearTokenStatus() {
      token_status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public user_account_record build() {
      try {
        user_account_record record = new user_account_record();
        record.action = fieldSetFlags()[0] ? this.action : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.verified = fieldSetFlags()[1] ? this.verified : (java.lang.Integer) defaultValue(fields()[1]);
        record.secret_token = fieldSetFlags()[2] ? this.secret_token : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.token_status = fieldSetFlags()[3] ? this.token_status : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
