/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.truecaller.logging.kafka.events;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class user_info_record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"user_info_record\",\"namespace\":\"com.truecaller.logging.kafka.events\",\"fields\":[{\"name\":\"device_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"provider_id\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"operator\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"screen_height\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"screen_width\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"app_language\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"client_id\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"build_name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"suspended\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"last_time\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"caller_id_plus_enabled\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"ip\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"imsi\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"oem\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"push_device_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"push_provider_id\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"os_var\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"os_name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"primary_service_country_code_name\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence device_id;
  @Deprecated public java.lang.Integer provider_id;
  @Deprecated public java.lang.CharSequence operator;
  @Deprecated public java.lang.CharSequence screen_height;
  @Deprecated public java.lang.CharSequence screen_width;
  @Deprecated public java.lang.CharSequence app_language;
  @Deprecated public java.lang.Integer client_id;
  @Deprecated public java.lang.CharSequence build_name;
  @Deprecated public java.lang.Integer suspended;
  @Deprecated public java.lang.Long last_time;
  @Deprecated public java.lang.Integer caller_id_plus_enabled;
  @Deprecated public java.lang.CharSequence ip;
  @Deprecated public java.lang.Long imsi;
  @Deprecated public java.lang.CharSequence oem;
  @Deprecated public java.lang.CharSequence push_device_id;
  @Deprecated public java.lang.Integer push_provider_id;
  @Deprecated public java.lang.CharSequence os_var;
  @Deprecated public java.lang.CharSequence os_name;
  @Deprecated public java.lang.CharSequence primary_service_country_code_name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public user_info_record() {}

  /**
   * All-args constructor.
   */
  public user_info_record(java.lang.CharSequence device_id, java.lang.Integer provider_id, java.lang.CharSequence operator, java.lang.CharSequence screen_height, java.lang.CharSequence screen_width, java.lang.CharSequence app_language, java.lang.Integer client_id, java.lang.CharSequence build_name, java.lang.Integer suspended, java.lang.Long last_time, java.lang.Integer caller_id_plus_enabled, java.lang.CharSequence ip, java.lang.Long imsi, java.lang.CharSequence oem, java.lang.CharSequence push_device_id, java.lang.Integer push_provider_id, java.lang.CharSequence os_var, java.lang.CharSequence os_name, java.lang.CharSequence primary_service_country_code_name) {
    this.device_id = device_id;
    this.provider_id = provider_id;
    this.operator = operator;
    this.screen_height = screen_height;
    this.screen_width = screen_width;
    this.app_language = app_language;
    this.client_id = client_id;
    this.build_name = build_name;
    this.suspended = suspended;
    this.last_time = last_time;
    this.caller_id_plus_enabled = caller_id_plus_enabled;
    this.ip = ip;
    this.imsi = imsi;
    this.oem = oem;
    this.push_device_id = push_device_id;
    this.push_provider_id = push_provider_id;
    this.os_var = os_var;
    this.os_name = os_name;
    this.primary_service_country_code_name = primary_service_country_code_name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return device_id;
    case 1: return provider_id;
    case 2: return operator;
    case 3: return screen_height;
    case 4: return screen_width;
    case 5: return app_language;
    case 6: return client_id;
    case 7: return build_name;
    case 8: return suspended;
    case 9: return last_time;
    case 10: return caller_id_plus_enabled;
    case 11: return ip;
    case 12: return imsi;
    case 13: return oem;
    case 14: return push_device_id;
    case 15: return push_provider_id;
    case 16: return os_var;
    case 17: return os_name;
    case 18: return primary_service_country_code_name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: device_id = (java.lang.CharSequence)value$; break;
    case 1: provider_id = (java.lang.Integer)value$; break;
    case 2: operator = (java.lang.CharSequence)value$; break;
    case 3: screen_height = (java.lang.CharSequence)value$; break;
    case 4: screen_width = (java.lang.CharSequence)value$; break;
    case 5: app_language = (java.lang.CharSequence)value$; break;
    case 6: client_id = (java.lang.Integer)value$; break;
    case 7: build_name = (java.lang.CharSequence)value$; break;
    case 8: suspended = (java.lang.Integer)value$; break;
    case 9: last_time = (java.lang.Long)value$; break;
    case 10: caller_id_plus_enabled = (java.lang.Integer)value$; break;
    case 11: ip = (java.lang.CharSequence)value$; break;
    case 12: imsi = (java.lang.Long)value$; break;
    case 13: oem = (java.lang.CharSequence)value$; break;
    case 14: push_device_id = (java.lang.CharSequence)value$; break;
    case 15: push_provider_id = (java.lang.Integer)value$; break;
    case 16: os_var = (java.lang.CharSequence)value$; break;
    case 17: os_name = (java.lang.CharSequence)value$; break;
    case 18: primary_service_country_code_name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'device_id' field.
   */
  public java.lang.CharSequence getDeviceId() {
    return device_id;
  }

  /**
   * Sets the value of the 'device_id' field.
   * @param value the value to set.
   */
  public void setDeviceId(java.lang.CharSequence value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'provider_id' field.
   */
  public java.lang.Integer getProviderId() {
    return provider_id;
  }

  /**
   * Sets the value of the 'provider_id' field.
   * @param value the value to set.
   */
  public void setProviderId(java.lang.Integer value) {
    this.provider_id = value;
  }

  /**
   * Gets the value of the 'operator' field.
   */
  public java.lang.CharSequence getOperator() {
    return operator;
  }

  /**
   * Sets the value of the 'operator' field.
   * @param value the value to set.
   */
  public void setOperator(java.lang.CharSequence value) {
    this.operator = value;
  }

  /**
   * Gets the value of the 'screen_height' field.
   */
  public java.lang.CharSequence getScreenHeight() {
    return screen_height;
  }

  /**
   * Sets the value of the 'screen_height' field.
   * @param value the value to set.
   */
  public void setScreenHeight(java.lang.CharSequence value) {
    this.screen_height = value;
  }

  /**
   * Gets the value of the 'screen_width' field.
   */
  public java.lang.CharSequence getScreenWidth() {
    return screen_width;
  }

  /**
   * Sets the value of the 'screen_width' field.
   * @param value the value to set.
   */
  public void setScreenWidth(java.lang.CharSequence value) {
    this.screen_width = value;
  }

  /**
   * Gets the value of the 'app_language' field.
   */
  public java.lang.CharSequence getAppLanguage() {
    return app_language;
  }

  /**
   * Sets the value of the 'app_language' field.
   * @param value the value to set.
   */
  public void setAppLanguage(java.lang.CharSequence value) {
    this.app_language = value;
  }

  /**
   * Gets the value of the 'client_id' field.
   */
  public java.lang.Integer getClientId() {
    return client_id;
  }

  /**
   * Sets the value of the 'client_id' field.
   * @param value the value to set.
   */
  public void setClientId(java.lang.Integer value) {
    this.client_id = value;
  }

  /**
   * Gets the value of the 'build_name' field.
   */
  public java.lang.CharSequence getBuildName() {
    return build_name;
  }

  /**
   * Sets the value of the 'build_name' field.
   * @param value the value to set.
   */
  public void setBuildName(java.lang.CharSequence value) {
    this.build_name = value;
  }

  /**
   * Gets the value of the 'suspended' field.
   */
  public java.lang.Integer getSuspended() {
    return suspended;
  }

  /**
   * Sets the value of the 'suspended' field.
   * @param value the value to set.
   */
  public void setSuspended(java.lang.Integer value) {
    this.suspended = value;
  }

  /**
   * Gets the value of the 'last_time' field.
   */
  public java.lang.Long getLastTime() {
    return last_time;
  }

  /**
   * Sets the value of the 'last_time' field.
   * @param value the value to set.
   */
  public void setLastTime(java.lang.Long value) {
    this.last_time = value;
  }

  /**
   * Gets the value of the 'caller_id_plus_enabled' field.
   */
  public java.lang.Integer getCallerIdPlusEnabled() {
    return caller_id_plus_enabled;
  }

  /**
   * Sets the value of the 'caller_id_plus_enabled' field.
   * @param value the value to set.
   */
  public void setCallerIdPlusEnabled(java.lang.Integer value) {
    this.caller_id_plus_enabled = value;
  }

  /**
   * Gets the value of the 'ip' field.
   */
  public java.lang.CharSequence getIp() {
    return ip;
  }

  /**
   * Sets the value of the 'ip' field.
   * @param value the value to set.
   */
  public void setIp(java.lang.CharSequence value) {
    this.ip = value;
  }

  /**
   * Gets the value of the 'imsi' field.
   */
  public java.lang.Long getImsi() {
    return imsi;
  }

  /**
   * Sets the value of the 'imsi' field.
   * @param value the value to set.
   */
  public void setImsi(java.lang.Long value) {
    this.imsi = value;
  }

  /**
   * Gets the value of the 'oem' field.
   */
  public java.lang.CharSequence getOem() {
    return oem;
  }

  /**
   * Sets the value of the 'oem' field.
   * @param value the value to set.
   */
  public void setOem(java.lang.CharSequence value) {
    this.oem = value;
  }

  /**
   * Gets the value of the 'push_device_id' field.
   */
  public java.lang.CharSequence getPushDeviceId() {
    return push_device_id;
  }

  /**
   * Sets the value of the 'push_device_id' field.
   * @param value the value to set.
   */
  public void setPushDeviceId(java.lang.CharSequence value) {
    this.push_device_id = value;
  }

  /**
   * Gets the value of the 'push_provider_id' field.
   */
  public java.lang.Integer getPushProviderId() {
    return push_provider_id;
  }

  /**
   * Sets the value of the 'push_provider_id' field.
   * @param value the value to set.
   */
  public void setPushProviderId(java.lang.Integer value) {
    this.push_provider_id = value;
  }

  /**
   * Gets the value of the 'os_var' field.
   */
  public java.lang.CharSequence getOsVar() {
    return os_var;
  }

  /**
   * Sets the value of the 'os_var' field.
   * @param value the value to set.
   */
  public void setOsVar(java.lang.CharSequence value) {
    this.os_var = value;
  }

  /**
   * Gets the value of the 'os_name' field.
   */
  public java.lang.CharSequence getOsName() {
    return os_name;
  }

  /**
   * Sets the value of the 'os_name' field.
   * @param value the value to set.
   */
  public void setOsName(java.lang.CharSequence value) {
    this.os_name = value;
  }

  /**
   * Gets the value of the 'primary_service_country_code_name' field.
   */
  public java.lang.CharSequence getPrimaryServiceCountryCodeName() {
    return primary_service_country_code_name;
  }

  /**
   * Sets the value of the 'primary_service_country_code_name' field.
   * @param value the value to set.
   */
  public void setPrimaryServiceCountryCodeName(java.lang.CharSequence value) {
    this.primary_service_country_code_name = value;
  }

  /** Creates a new user_info_record RecordBuilder */
  public static com.truecaller.logging.kafka.events.user_info_record.Builder newBuilder() {
    return new com.truecaller.logging.kafka.events.user_info_record.Builder();
  }
  
  /** Creates a new user_info_record RecordBuilder by copying an existing Builder */
  public static com.truecaller.logging.kafka.events.user_info_record.Builder newBuilder(com.truecaller.logging.kafka.events.user_info_record.Builder other) {
    return new com.truecaller.logging.kafka.events.user_info_record.Builder(other);
  }
  
  /** Creates a new user_info_record RecordBuilder by copying an existing user_info_record instance */
  public static com.truecaller.logging.kafka.events.user_info_record.Builder newBuilder(com.truecaller.logging.kafka.events.user_info_record other) {
    return new com.truecaller.logging.kafka.events.user_info_record.Builder(other);
  }
  
  /**
   * RecordBuilder for user_info_record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<user_info_record>
    implements org.apache.avro.data.RecordBuilder<user_info_record> {

    private java.lang.CharSequence device_id;
    private java.lang.Integer provider_id;
    private java.lang.CharSequence operator;
    private java.lang.CharSequence screen_height;
    private java.lang.CharSequence screen_width;
    private java.lang.CharSequence app_language;
    private java.lang.Integer client_id;
    private java.lang.CharSequence build_name;
    private java.lang.Integer suspended;
    private java.lang.Long last_time;
    private java.lang.Integer caller_id_plus_enabled;
    private java.lang.CharSequence ip;
    private java.lang.Long imsi;
    private java.lang.CharSequence oem;
    private java.lang.CharSequence push_device_id;
    private java.lang.Integer push_provider_id;
    private java.lang.CharSequence os_var;
    private java.lang.CharSequence os_name;
    private java.lang.CharSequence primary_service_country_code_name;

    /** Creates a new Builder */
    private Builder() {
      super(com.truecaller.logging.kafka.events.user_info_record.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.truecaller.logging.kafka.events.user_info_record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.device_id)) {
        this.device_id = data().deepCopy(fields()[0].schema(), other.device_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.provider_id)) {
        this.provider_id = data().deepCopy(fields()[1].schema(), other.provider_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.operator)) {
        this.operator = data().deepCopy(fields()[2].schema(), other.operator);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.screen_height)) {
        this.screen_height = data().deepCopy(fields()[3].schema(), other.screen_height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.screen_width)) {
        this.screen_width = data().deepCopy(fields()[4].schema(), other.screen_width);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.app_language)) {
        this.app_language = data().deepCopy(fields()[5].schema(), other.app_language);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.client_id)) {
        this.client_id = data().deepCopy(fields()[6].schema(), other.client_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.build_name)) {
        this.build_name = data().deepCopy(fields()[7].schema(), other.build_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.suspended)) {
        this.suspended = data().deepCopy(fields()[8].schema(), other.suspended);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.last_time)) {
        this.last_time = data().deepCopy(fields()[9].schema(), other.last_time);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.caller_id_plus_enabled)) {
        this.caller_id_plus_enabled = data().deepCopy(fields()[10].schema(), other.caller_id_plus_enabled);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ip)) {
        this.ip = data().deepCopy(fields()[11].schema(), other.ip);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.imsi)) {
        this.imsi = data().deepCopy(fields()[12].schema(), other.imsi);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.oem)) {
        this.oem = data().deepCopy(fields()[13].schema(), other.oem);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.push_device_id)) {
        this.push_device_id = data().deepCopy(fields()[14].schema(), other.push_device_id);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.push_provider_id)) {
        this.push_provider_id = data().deepCopy(fields()[15].schema(), other.push_provider_id);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.os_var)) {
        this.os_var = data().deepCopy(fields()[16].schema(), other.os_var);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.os_name)) {
        this.os_name = data().deepCopy(fields()[17].schema(), other.os_name);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.primary_service_country_code_name)) {
        this.primary_service_country_code_name = data().deepCopy(fields()[18].schema(), other.primary_service_country_code_name);
        fieldSetFlags()[18] = true;
      }
    }
    
    /** Creates a Builder by copying an existing user_info_record instance */
    private Builder(com.truecaller.logging.kafka.events.user_info_record other) {
            super(com.truecaller.logging.kafka.events.user_info_record.SCHEMA$);
      if (isValidValue(fields()[0], other.device_id)) {
        this.device_id = data().deepCopy(fields()[0].schema(), other.device_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.provider_id)) {
        this.provider_id = data().deepCopy(fields()[1].schema(), other.provider_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.operator)) {
        this.operator = data().deepCopy(fields()[2].schema(), other.operator);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.screen_height)) {
        this.screen_height = data().deepCopy(fields()[3].schema(), other.screen_height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.screen_width)) {
        this.screen_width = data().deepCopy(fields()[4].schema(), other.screen_width);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.app_language)) {
        this.app_language = data().deepCopy(fields()[5].schema(), other.app_language);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.client_id)) {
        this.client_id = data().deepCopy(fields()[6].schema(), other.client_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.build_name)) {
        this.build_name = data().deepCopy(fields()[7].schema(), other.build_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.suspended)) {
        this.suspended = data().deepCopy(fields()[8].schema(), other.suspended);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.last_time)) {
        this.last_time = data().deepCopy(fields()[9].schema(), other.last_time);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.caller_id_plus_enabled)) {
        this.caller_id_plus_enabled = data().deepCopy(fields()[10].schema(), other.caller_id_plus_enabled);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ip)) {
        this.ip = data().deepCopy(fields()[11].schema(), other.ip);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.imsi)) {
        this.imsi = data().deepCopy(fields()[12].schema(), other.imsi);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.oem)) {
        this.oem = data().deepCopy(fields()[13].schema(), other.oem);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.push_device_id)) {
        this.push_device_id = data().deepCopy(fields()[14].schema(), other.push_device_id);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.push_provider_id)) {
        this.push_provider_id = data().deepCopy(fields()[15].schema(), other.push_provider_id);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.os_var)) {
        this.os_var = data().deepCopy(fields()[16].schema(), other.os_var);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.os_name)) {
        this.os_name = data().deepCopy(fields()[17].schema(), other.os_name);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.primary_service_country_code_name)) {
        this.primary_service_country_code_name = data().deepCopy(fields()[18].schema(), other.primary_service_country_code_name);
        fieldSetFlags()[18] = true;
      }
    }

    /** Gets the value of the 'device_id' field */
    public java.lang.CharSequence getDeviceId() {
      return device_id;
    }
    
    /** Sets the value of the 'device_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setDeviceId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.device_id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'device_id' field has been set */
    public boolean hasDeviceId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'device_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'provider_id' field */
    public java.lang.Integer getProviderId() {
      return provider_id;
    }
    
    /** Sets the value of the 'provider_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setProviderId(java.lang.Integer value) {
      validate(fields()[1], value);
      this.provider_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'provider_id' field has been set */
    public boolean hasProviderId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'provider_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearProviderId() {
      provider_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'operator' field */
    public java.lang.CharSequence getOperator() {
      return operator;
    }
    
    /** Sets the value of the 'operator' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setOperator(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.operator = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'operator' field has been set */
    public boolean hasOperator() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'operator' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearOperator() {
      operator = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'screen_height' field */
    public java.lang.CharSequence getScreenHeight() {
      return screen_height;
    }
    
    /** Sets the value of the 'screen_height' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setScreenHeight(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.screen_height = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'screen_height' field has been set */
    public boolean hasScreenHeight() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'screen_height' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearScreenHeight() {
      screen_height = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'screen_width' field */
    public java.lang.CharSequence getScreenWidth() {
      return screen_width;
    }
    
    /** Sets the value of the 'screen_width' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setScreenWidth(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.screen_width = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'screen_width' field has been set */
    public boolean hasScreenWidth() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'screen_width' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearScreenWidth() {
      screen_width = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'app_language' field */
    public java.lang.CharSequence getAppLanguage() {
      return app_language;
    }
    
    /** Sets the value of the 'app_language' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setAppLanguage(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.app_language = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'app_language' field has been set */
    public boolean hasAppLanguage() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'app_language' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearAppLanguage() {
      app_language = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'client_id' field */
    public java.lang.Integer getClientId() {
      return client_id;
    }
    
    /** Sets the value of the 'client_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setClientId(java.lang.Integer value) {
      validate(fields()[6], value);
      this.client_id = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'client_id' field has been set */
    public boolean hasClientId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'client_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearClientId() {
      client_id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'build_name' field */
    public java.lang.CharSequence getBuildName() {
      return build_name;
    }
    
    /** Sets the value of the 'build_name' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setBuildName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.build_name = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'build_name' field has been set */
    public boolean hasBuildName() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'build_name' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearBuildName() {
      build_name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'suspended' field */
    public java.lang.Integer getSuspended() {
      return suspended;
    }
    
    /** Sets the value of the 'suspended' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setSuspended(java.lang.Integer value) {
      validate(fields()[8], value);
      this.suspended = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'suspended' field has been set */
    public boolean hasSuspended() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'suspended' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearSuspended() {
      suspended = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'last_time' field */
    public java.lang.Long getLastTime() {
      return last_time;
    }
    
    /** Sets the value of the 'last_time' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setLastTime(java.lang.Long value) {
      validate(fields()[9], value);
      this.last_time = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'last_time' field has been set */
    public boolean hasLastTime() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'last_time' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearLastTime() {
      last_time = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'caller_id_plus_enabled' field */
    public java.lang.Integer getCallerIdPlusEnabled() {
      return caller_id_plus_enabled;
    }
    
    /** Sets the value of the 'caller_id_plus_enabled' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setCallerIdPlusEnabled(java.lang.Integer value) {
      validate(fields()[10], value);
      this.caller_id_plus_enabled = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'caller_id_plus_enabled' field has been set */
    public boolean hasCallerIdPlusEnabled() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'caller_id_plus_enabled' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearCallerIdPlusEnabled() {
      caller_id_plus_enabled = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'ip' field */
    public java.lang.CharSequence getIp() {
      return ip;
    }
    
    /** Sets the value of the 'ip' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setIp(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.ip = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'ip' field has been set */
    public boolean hasIp() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'ip' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearIp() {
      ip = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'imsi' field */
    public java.lang.Long getImsi() {
      return imsi;
    }
    
    /** Sets the value of the 'imsi' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setImsi(java.lang.Long value) {
      validate(fields()[12], value);
      this.imsi = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'imsi' field has been set */
    public boolean hasImsi() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'imsi' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearImsi() {
      imsi = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'oem' field */
    public java.lang.CharSequence getOem() {
      return oem;
    }
    
    /** Sets the value of the 'oem' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setOem(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.oem = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'oem' field has been set */
    public boolean hasOem() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'oem' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearOem() {
      oem = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'push_device_id' field */
    public java.lang.CharSequence getPushDeviceId() {
      return push_device_id;
    }
    
    /** Sets the value of the 'push_device_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setPushDeviceId(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.push_device_id = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'push_device_id' field has been set */
    public boolean hasPushDeviceId() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'push_device_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearPushDeviceId() {
      push_device_id = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'push_provider_id' field */
    public java.lang.Integer getPushProviderId() {
      return push_provider_id;
    }
    
    /** Sets the value of the 'push_provider_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setPushProviderId(java.lang.Integer value) {
      validate(fields()[15], value);
      this.push_provider_id = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'push_provider_id' field has been set */
    public boolean hasPushProviderId() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'push_provider_id' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearPushProviderId() {
      push_provider_id = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'os_var' field */
    public java.lang.CharSequence getOsVar() {
      return os_var;
    }
    
    /** Sets the value of the 'os_var' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setOsVar(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.os_var = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'os_var' field has been set */
    public boolean hasOsVar() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'os_var' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearOsVar() {
      os_var = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'os_name' field */
    public java.lang.CharSequence getOsName() {
      return os_name;
    }
    
    /** Sets the value of the 'os_name' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setOsName(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.os_name = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'os_name' field has been set */
    public boolean hasOsName() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'os_name' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearOsName() {
      os_name = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'primary_service_country_code_name' field */
    public java.lang.CharSequence getPrimaryServiceCountryCodeName() {
      return primary_service_country_code_name;
    }
    
    /** Sets the value of the 'primary_service_country_code_name' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder setPrimaryServiceCountryCodeName(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.primary_service_country_code_name = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'primary_service_country_code_name' field has been set */
    public boolean hasPrimaryServiceCountryCodeName() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'primary_service_country_code_name' field */
    public com.truecaller.logging.kafka.events.user_info_record.Builder clearPrimaryServiceCountryCodeName() {
      primary_service_country_code_name = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    @Override
    public user_info_record build() {
      try {
        user_info_record record = new user_info_record();
        record.device_id = fieldSetFlags()[0] ? this.device_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.provider_id = fieldSetFlags()[1] ? this.provider_id : (java.lang.Integer) defaultValue(fields()[1]);
        record.operator = fieldSetFlags()[2] ? this.operator : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.screen_height = fieldSetFlags()[3] ? this.screen_height : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.screen_width = fieldSetFlags()[4] ? this.screen_width : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.app_language = fieldSetFlags()[5] ? this.app_language : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.client_id = fieldSetFlags()[6] ? this.client_id : (java.lang.Integer) defaultValue(fields()[6]);
        record.build_name = fieldSetFlags()[7] ? this.build_name : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.suspended = fieldSetFlags()[8] ? this.suspended : (java.lang.Integer) defaultValue(fields()[8]);
        record.last_time = fieldSetFlags()[9] ? this.last_time : (java.lang.Long) defaultValue(fields()[9]);
        record.caller_id_plus_enabled = fieldSetFlags()[10] ? this.caller_id_plus_enabled : (java.lang.Integer) defaultValue(fields()[10]);
        record.ip = fieldSetFlags()[11] ? this.ip : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.imsi = fieldSetFlags()[12] ? this.imsi : (java.lang.Long) defaultValue(fields()[12]);
        record.oem = fieldSetFlags()[13] ? this.oem : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.push_device_id = fieldSetFlags()[14] ? this.push_device_id : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.push_provider_id = fieldSetFlags()[15] ? this.push_provider_id : (java.lang.Integer) defaultValue(fields()[15]);
        record.os_var = fieldSetFlags()[16] ? this.os_var : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.os_name = fieldSetFlags()[17] ? this.os_name : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.primary_service_country_code_name = fieldSetFlags()[18] ? this.primary_service_country_code_name : (java.lang.CharSequence) defaultValue(fields()[18]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
